services:
    jurv_doctrine_encrypt.orm_subscriber:
        class: Jurv\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@annotation_reader", "%jurv_doctrine_encrypt.encryptor_class_name%", "%jurv_doctrine_encrypt.secret_key%"]
        tags:
            -  { name: doctrine.event_subscriber }
    jurv_doctrine_encrypt.subscriber:
        alias: jurv_doctrine_encrypt.orm_subscriber
    jurv_doctrine_encrypt.encryptor:
        class: Jurv\DoctrineEncryptBundle\Services\Encryptor
        arguments:
            - "%jurv_doctrine_encrypt.encryptor_class_name%"
            - "%jurv_doctrine_encrypt.secret_key%"
